### ISSUE TITLE
What errors does it catch?

### ISSUE THREAD

**Issue by rstacruz** [denis-sokolov/strict-standard#1]
Some examples would be nice.

**Comment by denis-sokolov** [comment]
Some of the most common are catching [misspelled variables](http://eslint.org/docs/rules/no-unused-vars) and accidental [shadowing of variables](http://eslint.org/docs/rules/no-shadow):

``` js
function(cb){
  var result = 1;
  cb(resuit);
}
```

```
function(cb){
  doThing1(function(cb){
    cb(42);
  });
}
```

With error checking this will inform you right away that the code above is likely broken in both cases.

Check [Error Explanations](https://jslinterrors.com/?linter=eslint) created for clarifying all linter rules.
